import Head from "next/head";

import { VscNewFile, VscFiles } from "react-icons/vsc";

export default function Home() {
  function dropping(e) {
    console.log("drop");
    for (const f of e.dataTransfer.files) {
      console.log("File(s) you dragged here: ", f.path);
      electron.ipcRenderer.send("read-file", f.path);
    }
  }

  return (
    <div
      className="h-full bg-blue-500"
      onDragOver={(e) => e.preventDefault()}
      onDrop={(e) => dropping(e)}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full">
        <div className="flex h-full gap-8 justify-center items-center">
          <div className="flex flex-col cursor-pointer gap-4 items-center">
            <VscNewFile fontSize={68} />
            <h1>New</h1>
          </div>
          <div className="flex flex-col cursor-pointer gap-4 items-center">
            <VscFiles fontSize={68} />
            <h1>Browse</h1>
          </div>
        </div>
      </main>
    </div>
  );
}
